version: "2"

linters:
  default: standard
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - copyloopvar

formatters:
  enable:
    - gofmt
    - goimports
